### ISSUE TITLE
Can't login with horizontal screen orientation

### ISSUE THREAD

**Issue by waytoroot** [poVoq/conversejs-ubports#7]
I can't login with horizontal screen orientation (BQ Aquaris M10FDH).
When the buttons are pressed, nothing happens.
When screen orientation horizontal login is successful.

**Comment by poVoq** [comment]
Thanks for the feedback. No idea what might be causing it as the login screen is only a simple HTML page rendered with qwebengine.
I have a partially working complete remake of the login page in the works that I will probably complete when ConverseJS is updated to 7.0. I guess that would fix it.

Any other issue with the BQ? I can currently only testy with my Nexus5 and I don't receive much feedback from other devices.

**Comment by waytoroot** [comment]
the login page seems to overlap the chat page. 
there are no other problems yet. 
thanks!

**Comment by poVoq** [comment]
Hmm, which login page are we actually talking about? Did you somehow manage to get to the internal one from ConverseJS? Or the horrible looking one I stapled in front of it with HTML?
Because ConverseJS isn't actually loaded before pressing the "login" button on my HTML login page.

But I think I might know what the problem might be. The ConverseJS "mobile" view-mode turns blank and breaks if the horizontal screen resolution is big enough that it thinks it is on a Tablet or Desktop PC. So I think it might show my HTML login screen again in horizontal mode as the ConverseJS chat is overlayed on top of it, but then ConverseJS is already fully loaded and you can not login in again. So right now tablets or anything with a high horizontal screen resolution isn't really supported.

In the new login page I am working on there will be a toggle that allows to switch to the "fullscreen" view-mode that is more suited for Desktop PCs and I guess tablets.
But I also hope that in an upcoming version of ConverseJS the "mobile" view-mode is merged with the "fullscreen" view-mode so that everything is fully convergent. Lets see :)

**Comment by waytoroot** [comment]
Watch this https://youtu.be/j8lhn-3q_o4 ;-)

**Comment by poVoq** [comment]
Yeah, that confirms my suspicion what is causing it. It's an upstream issue with the "mobile" view-mode in Conversejs. I'll try to see if there is a quick fix, otherwise it will have to wait for the "tablet/desktop mode toggle" setting I was talking about earlier.

**Comment by waytoroot** [comment]
Ok, thx. Really in desktop mode, it works correctly.

**Comment by boroli** [comment]
Same problem here on a PinePhone CE, once I rotate the display into landscape mode.

**Comment by poVoq** [comment]
Yes this is a bug that will take time to solve. I am actually thinking about re-basing this app on Chimeverse, the recently made official desktop electron client of ConverseJS, as that would probably solve this and many other issues.
It is on my todo once ConverseJS 7.0 is released, but of course if someone else wants to give it a go that would be great (I am actually not using UT much these days due to hardware issues with my Nexus5).

**Comment by poVoq** [comment]
Should be fixed in version 7.0.6. with the new bootstrapped login page.
